#!/usr/bin/env python

import sys
import pybitcointools

def usage():
    print "usage: xpub-addresses <xpub> <m> <n>"
    sys.exit(1)

if len(sys.argv) != 4:
    usage()

xpub = sys.argv[1]
m = int(sys.argv[2])
n = int(sys.argv[3])

if xpub[0:4] == "xpub":
    # BIP44
    dpk1 = pybitcointools.bip32_ckd(xpub, m)
    for i in range(0, n):
        dpk2 = pybitcointools.bip32_ckd(dpk1, i)
        pubkey = pybitcointools.bip32_extract_key(dpk2)
        address = pybitcointools.pubkey_to_address(pubkey)
        print address
else:
    print "argument is not an xpub: {}".format(xpub)
    sys.exit(1)

